apiVersion : apps/v1
kind: Deployment
metadata:
  name: "akslabs-69ed"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "akslabs-69ed"
  template:
    metadata:
      labels:
        app: "akslabs-69ed"
    spec:
      containers:
        - name: "akslabs-69ed"
          image: "acrlabs2234.azurecr.io/akslabs"
          ports:
          - containerPort: 80